apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: sentiment
images:
  - name: ghcr.io/yunajeon/ez-mlops-project/sentiment-api
    newTag: prod-ca4ab82
