name: ci

on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - 'k8s/overlays/prod/kustomization.yaml'
  pull_request:

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  test-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install --index-url https://download.pytorch.org/whl/cpu torch==2.4.1
          pip install -r requirements.txt

      - name: Unit tests (fast)
        env:
          PYTHONPATH: .
          ENABLE_TRACING: "false"
          OTEL_EXPORTER_OTLP_ENDPOINT: ""
        run: |
          pytest -q -m "not e2e"

      - name: Set image tag
        id: tag
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "IMAGE_TAG=prod-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Docker build
        run: |
          docker build -f docker/Dockerfile -t sentiment-api:${IMAGE_TAG} .

      - name: Smoke test container
        run: |
          docker run -d --name api -p 8000:8000 -e ENABLE_TRACING=false -e OTEL_EXPORTER_OTLP_ENDPOINT="" sentiment-api:${IMAGE_TAG}
          
          for i in {1..60}; do
            if curl -sf http://localhost:8000/readyz >/dev/null; then
              echo "ready"
              break
            fi
            sleep 2
          done

          curl -sf http://localhost:8000/healthz
          curl -sf http://localhost:8000/readyz
          curl -sf -X POST http://localhost:8000/v1/predict -H 'Content-Type: application/json' -d '{"text":"실적이 좋아 주가가 올랐다."}'
          docker logs api --tail 200
          docker rm -f api

      - name: Update prod image tag in kustomization
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i "s/newTag: .*/newTag: ${IMAGE_TAG}/" k8s/overlays/prod/kustomization.yaml

      - name: Commit and push tag update
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git add k8s/overlays/prod/kustomization.yaml
          git commit -m "chore: update prod image tage to ${IMAGE_TAG}" || echo "No changes"
          git push
