apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -stg
namespace: sentiment
images:
  - name: ghcr.io/your-org/sentiment-api
    newTag: stg-CHANGE_ME
